# Production environment
spring.mongodb.uri=${MONGODB_URI_PROD}
spring.mongodb.database=${MONGODB_DATABASE_PROD:prod}
server.port=8082

gcp.storage.bucket-name=${GCS_BUCKET_NAME:}
gcp.storage.project-id=${GCS_PROJECT_ID:}
gcp.storage.credentials-path=${GCS_CREDENTIALS_PATH:}

# Multipart File Size Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB